export const ADD_TASK_PENDING = "ADD_TASK_PENDING";
export const EDIT_TASK_PENDING = "EDIT_TASK_PENDING";
export const REMOVE_TASK_PENDING = "REMOVE_TASK_PENDING";
export const SET_TASK_PENDING = "SET_TASK_PENDING";

export const ADD_TASK_COMPLETED = "ADD_TASK_COMPLETED";
export const EDIT_TASK_COMPLETED = "EDIT_TASK_COMPLETED";
export const REMOVE_TASK_COMPLETED = "REMOVE_TASK_COMPLETED";
export const SET_TASK_COMPLETED = "SET_TASK_COMPLETED";

export const ADD_TASK_IMPORTANT = "ADD_TASK_IMPORTANT";
export const EDIT_TASK_IMPORTANT = "EDIT_TASK_IMPORTANT";
export const REMOVE_TASK_IMPORTANT = "REMOVE_TASK_IMPORTANT";
export const SET_TASK_IMPORTANT = "SET_TASK_IMPORTANT";

export const ADD_NOTE = "ADD_NOTE";
export const EDIT_NOTE = "EDIT_NOTE";
export const REMOVE_NOTE = "REMOVE_NOTE";
export const REMOVE_ALL_NOTES = "REMOVE_ALL_NOTES";
export const SET_NOTES = "SET_NOTES";
